/****************************************************************************

 Copyright (C) 1997 Marius Greuel. All rights reserved.

 Title:		helpids.cpp : mapping from resource id to help id

 Version:	1.00

 Date:		15-Jan-97

 Author:	MG

****************************************************************************/

#include "stdafx.h"

#include "resource.h"
#include "resource.hm"

DWORD g_aHelpIDs[] = {
	ID_TEST_LEFT_JOY,		HID_TEST_LEFT_JOY,
	ID_TEST_RIGHT_JOY,		HID_TEST_LEFT_JOY,
	ID_TEST_LEFT_BAR,		HID_TEST_LEFT_BAR,
	ID_TEST_RIGHT_BAR,		HID_TEST_LEFT_BAR,
	ID_TEST_CHANNEL1,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL2,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL3,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL4,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL5,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL6,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL7,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL8,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL9,		HID_TEST_CHANNEL1,
	ID_TEST_CHANNEL10,		HID_TEST_CHANNEL1,
	ID_TEST_STATUS,			HID_TEST_STATUS,

	IDNEXT,					HIDNEXT,
	IDPREV,					HIDPREV,
	ID_CAL_COMMAND,			HID_CAL_COMMAND,
	ID_CAL_BAR1,			HID_CAL_BAR1,
	
	ID_EXT_PULSE_SYNC,		HID_EXT_PULSE_SYNC,
	ID_EXT_UD_PSYNC,		HID_EXT_PULSE_SYNC,
	ID_EXT_PULSE_MIDDLE,	HID_EXT_PULSE_MIDDLE,
	ID_EXT_UD_PMIDDLE,		HID_EXT_PULSE_MIDDLE,
	ID_EXT_PULSE_MAX,		HID_EXT_PULSE_MAX,
	ID_EXT_UD_PMAX,			HID_EXT_PULSE_MAX,
	ID_EXT_INVPULSE,		HID_EXT_INVPULSE,
	ID_EXT_COM_PORT,		HID_EXT_COM_PORT,
	ID_EXT_COM_IRQ,			HID_EXT_COM_IRQ,

	0,0
};


