//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by version.rc
//
#define VER_FILESUBTYPE                 0
#define VER_DEBUG                       0
#define VER_PRERELEASE                  0
#define VER_MFS_MAJOR                   1
#define VER_MFS_MINOR                   1
#define VER_PRODUCTBUILD                1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
